export type GatewayMessage = {
	code: number;
	data: any;
	sequence?: number;
	event?: string;
};

export enum GatewayOpCode {
	Dispatch = 0,
	Heartbeat = 1,
	Identify = 2,
	PresenceUpdate = 3,
	VoiceStateUpdate = 4,
	VoiceServerPing = 5,
	Resume = 6,
	Reconnect = 7,
	RequestGuildMembers = 8,
	InvalidSession = 9,
	Hello = 10,
	HeartbeatACK = 11,
	CallConnect = 13,
	LobbyVoiceStates = 17,
	StreamCreate = 18,
	StreamDelete = 19,
	StreamWatch = 20,
	StreamPing = 21,
	StreamSetPaused = 22,
	RequestForumUnreads = 28,
	RemoteCommand = 29,
	RequestDeletedEntityIDs = 30,
	RequestSoundboardSounds = 31,
	RequestLastMessages = 34,
	SearchRecentMembers = 35,
	GuildSubscriptionsBulk = 37,
	GuildChannelsResync = 38,
	RequestChannelMemberCount = 39,
	QoSHeartbeat = 40,
	UpdateTimeSpentSessionID = 41,
	LobbyVoiceServerPing = 42,
	RequestChannelInfo = 43
};

export enum GatewayEvent {
	Heartbeat = "heartbeat",
	Connecting = "connecting",
	Disconnected = "disconnected",
	Resumed = "resumed"
};

export enum GatewayDispatchEvent {
	Ready = "READY",
	ReadySupplemental = "READY_SUPPLEMENTAL",
	Resumed = "RESUMED",
	SessionsReplace = "SESSIONS_REPLACE",
	UserSettingsProtoUpdate = "USER_SETTINGS_PROTO_UPDATE",
	UserSettingsUpdate = "USER_SETTINGS_UPDATE",
	ApplicationCommandPermissionsUpdate = "APPLICATION_COMMAND_PERMISSIONS_UPDATE",
	AutoModerationRuleCreate = "AUTO_MODERATION_RULE_CREATE",
	AutoModerationRuleUpdate = "AUTO_MODERATION_RULE_UPDATE",
	AutoModerationRuleDelete = "AUTO_MODERATION_RULE_DELETE",
	AutoModerationActionExecution = "AUTO_MODERATION_ACTION_EXECUTION",
	ChannelCreate = "CHANNEL_CREATE",
	ChannelUpdate = "CHANNEL_UPDATE",
	ChannelDelete = "CHANNEL_DELETE",
	ChannelPinsUpdate = "CHANNEL_PINS_UPDATE",
	ThreadCreate = "THREAD_CREATE",
	ThreadUpdate = "THREAD_UPDATE",
	ThreadDelete = "THREAD_DELETE",
	ThreadListSync = "THREAD_LIST_SYNC",
	ThreadMemberUpdate = "THREAD_MEMBER_UPDATE",
	ThreadMembersUpdate = "THREAD_MEMBERS_UPDATE",
	GuildCreate = "GUILD_CREATE",
	GuildUpdate = "GUILD_UPDATE",
	GuildDelete = "GUILD_DELETE",
	GuildBanAdd = "GUILD_BAN_ADD",
	GuildBanRemove = "GUILD_BAN_REMOVE",
	GuildEmojisUpdate = "GUILD_EMOJIS_UPDATE",
	GuildStickersUpdate = "GUILD_STICKERS_UPDATE",
	GuildIntegrationsUpdate = "GUILD_INTEGRATIONS_UPDATE",
	GuildMemberAdd = "GUILD_MEMBER_ADD",
	GuildMemberUpdate = "GUILD_MEMBER_UPDATE",
	GuildMemberRemove = "GUILD_MEMBER_REMOVE",
	GuildMembersChunk = "GUILD_MEMBERS_CHUNK",
	GuildRoleCreate = "GUILD_ROLE_CREATE",
	GuildRoleUpdate = "GUILD_ROLE_UPDATE",
	GuildRoleDelete = "GUILD_ROLE_DELETE",
	GuildScheduledEventCreate = "GUILD_SCHEDULED_EVENT_CREATE",
	GuildScheduledEventUpdate = "GUILD_SCHEDULED_EVENT_UPDATE",
	GuildScheduledEventDelete = "GUILD_SCHEDULED_EVENT_DELETE",
	GuildScheduledEventUserAdd = "GUILD_SCHEDULED_EVENT_USER_ADD",
	GuildScheduledEventUserRemove = "GUILD_SCHEDULED_EVENT_USER_REMOVE",
	GuildAuditLogEntryCreate = "GUILD_AUDIT_LOG_ENTRY_CREATE",
	IntegrationCreate = "INTEGRATION_CREATE",
	IntegrationUpdate = "INTEGRATION_UPDATE",
	IntegrationDelete = "INTEGRATION_DELETE",
	InviteCreate = "INVITE_CREATE",
	InviteDelete = "INVITE_DELETE",
	MessageCreate = "MESSAGE_CREATE",
	MessageUpdate = "MESSAGE_UPDATE",
	MessageDelete = "MESSAGE_DELETE",
	MessageDeleteBulk = "MESSAGE_DELETE_BULK",
	LastMessages = "LAST_MESSAGES",
	MessageReactionAdd = "MESSAGE_REACTION_ADD",
	MessageReactionRemove = "MESSAGE_REACTION_REMOVE",
	MessageReactionRemoveAll = "MESSAGE_REACTION_REMOVE_ALL",
	MessageReactionRemoveEmoji = "MESSAGE_REACTION_REMOVE_EMOJI",
	PresenceUpdate = "PRESENCE_UPDATE",
	StageInstanceCreate = "STAGE_INSTANCE_CREATE",
	StageInstanceUpdate = "STAGE_INSTANCE_UPDATE",
	StageInstanceDelete = "STAGE_INSTANCE_DELETE",
	TypingStart = "TYPING_START",
	UserUpdate = "USER_UPDATE",
	VoiceStateUpdate = "VOICE_STATE_UPDATE",
	VoiceServerUpdate = "VOICE_SERVER_UPDATE",
	WebhooksUpdate = "WEBHOOKS_UPDATE",
	InteractionCreate = "INTERACTION_CREATE",
	EntitlementCreate = "ENTITLEMENT_CREATE",
	EntitlementUpdate = "ENTITLEMENT_UPDATE",
	EntitlementDelete = "ENTITLEMENT_DELETE",
	GuildMemberListUpdate = "GUILD_MEMBER_LIST_UPDATE",
	CallCreate = "CALL_CREATE",
	CallUpdate = "CALL_UPDATE",
	CallDelete = "CALL_DELETE",
	ChannelRecipientAdd = "CHANNEL_RECIPIENT_ADD",
	ChannelRecipientRemove = "CHANNEL_RECIPIENT_REMOVE",
	FriendSuggestionCreate = "FRIEND_SUGGESTION_CREATE",
	FriendSuggestionDelete = "FRIEND_SUGGESTION_DELETE",
	UserConnectionsUpdate = "USER_CONNECTIONS_UPDATE",
	UserNoteUpdate = "USER_NOTE_UPDATE",
	UserRequiredActionUpdate = "USER_REQUIRED_ACTION_UPDATE",
	RelationshipAdd = "RELATIONSHIP_ADD",
	RelationshipRemove = "RELATIONSHIP_REMOVE",
	PresenceReplace = "PRESENCE_REPLACE",
	GuildJoinRequestCreate = "GUILD_JOIN_REQUEST_CREATE",
	GuildJoinRequestUpdate = "GUILD_JOIN_REQUEST_UPDATE",
	GuildJoinRequestDelete = "GUILD_JOIN_REQUEST_DELETE",
	RecentMentionDelete = "RECENT_MENTION_DELETE"
};

export enum GatewayCloseCode {
	UnknownError = 4000,
	UnknownOpcode = 4001,
	DecodeError = 4002,
	NotAuthenticated = 4003,
	AuthenticationFailed = 4004,
	AlreadyAuthenticated = 4005,
	InvalidSeq = 4007,
	RateLimited = 4008,
	SessionTimeout = 4009,
	InvalidShard = 4010,
	ShardingRequired = 4011,
	InvalidApiVersion = 4012,
	InvalidIntents = 4013,
	DisallowedIntents = 4014
};

export const GatewayIntents = {
	LazyUserNotes: 1n << 0n,
	NoAffineUserIds: 1n << 1n,
	VersionedReadStates: 1n << 2n,
	VersionedUserGuildSettings: 1n << 3n,
	DedupeUserObjects: 1n << 4n,
	PrioritizedReadyPayload: 1n << 5n,
	MultipleGuildExperimentPopulations: 1n << 6n,
	NonChannelReadStates: 1n << 7n,
	AuthTokenRefresh: 1n << 8n,
	UserSettingsProto: 1n << 9n,
	ClientStateV2: 1n << 10n,
	PassiveGuildUpdate: 1n << 11n,
	AutoCallConnect: 1n << 12n,
	DebounceMessageReactions: 1n << 13n,
	PassiveGuildUpdateV2: 1n << 14n,
	ChannelObfuscation: 1n << 15n,
	AutoLobbyConnect: 1n << 16n
} as const;
export type GatewayIntents = typeof GatewayIntents[keyof typeof GatewayIntents];